dist: bionic

language: go

env: GO111MODULE=on

go:
  - 1.13.x
  - 1.14.x

# Only clone the most recent commit.
git:
  depth: 1

notifications:
  email: false

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.24.0

script:
  - make lint
  - make test


before_deploy:
  - go build ./cmd/copy-basta

deploy:
  provider: releases
  api_key: $AUTH_TOKEN
  file: copy-basta
  skip_cleanup: true
  draft: true
  on:
    tags: true
