dist: bionic

language: go

env: GO111MODULE=on

go:
  - 1.13.x
  - 1.14.x

# Only clone the most recent commit.
git:
  depth: 1

notifications:
  email: false

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.24.0

script:
  - make lint
  - make test


before_deploy:
  - go build ./cmd/copy-basta

# GITHUB_PERSONAL_ACCESS_TOKEN
# 1) go to https://github.com/settings/tokens
# 2) generate token with `repo` scopes
# 3) add key to travis env variables
deploy:
  provider: releases
  api_key: $GITHUB_PERSONAL_ACCESS_TOKEN
  file:
  - ./copy-basta
  skip_cleanup: true
  name: v$TRAVIS_TAG
  body: "This is the body"
  draft: true
  prerelease: false
  on:
    tags: true
    condition: $TRAVIS_GO_VERSION =~ ^1\.14
